apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitio-web
  template:
    metadata:
      labels:
        app: sitio-web
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sitio-volumen
              mountPath: /usr/share/nginx/html
      volumes:
        - name: sitio-volumen
          persistentVolumeClaim:
            claimName: sitio-pvc
