apiVersion: v1
kind: PersistentVolume
metadata:
  name: sitio-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/web

